- README.md
- openfoodfacts/facets.py
- setup.py
* It was discussed in my previous PR #1, a few mistakes were left inside the README and setup.py. There were wrong in several places. This PR fixes them.
* Add documentation to README.
* Remove a duplicate in the facet list.
> Minor improvements and fixes

- .travis.yml
- openfoodfacts/__init__.py
- openfoodfacts/products.py
- openfoodfacts/utils.py
- tests/facets_test.py
- tests/products_test.py
Problem: Travis build is broken.
* Add a Travis config to make sure that tests are runned in a proper environment.
* Make sure that the code is pep8 compliant. That way, the pep8 checking done by Travis doesn't return any error.
> Add Travis config and make the code pep8 compliant

- openfoodfacts/__init__.py
- openfoodfacts/products.py
- openfoodfacts/utils.py
Problem: the API doesn't work with Python 3.
These changes should allow import and usage of this lib in a Python 3 environment.
> Make code compatible with Python 3

- README.md
- openfoodfacts/__init__.py
- openfoodfacts/products.py
- tests/products_test.py
* Fix Build.
* Add documentation for `products.get_by_facets()`.
* Handle properly an edge case of get  `products.get_by_facets()` (when no facet is given).
> Minor improvements

- openfoodfacts/autosuggest.py
Problem: Pep8 validation is broken
Solution: Fix the code syntax
> Fix PEP8 in autosuggest module

- README.md
- openfoodfacts/__init__.py
- openfoodfacts/products.py
- tests/facets_test.py
- tests/products_test.py
* Fix urls in test mocks
* Fix #18 
* Allow to fetch a given page for a given facet
* Fix #22
> Fix tests and allow to fetch a given page

- openfoodfacts/products.py
**Problem**
The current search function has only a limited functionality and can only search for specific terms.
**Solution**
Using this advanced search option user can pass in any [parameters](https://en.wiki.openfoodfacts.org/API/Read/Search#Parameters) in a dictionary format and this function will return a json object.
Example:-
```
postData = {
"search_terms":"coke",
"tagtype_0":"packaging",
"tag_contains_0":"contains",
"tag_0":"plastic",
"nutriment_0":"energy",
"nutriment_compare_0":"gt",
"nutriment_value_0":"0",
"sort_by":"unique_scans",
"page_size":"20"
}
```
```
searched_product=products.advanced_search(postData)
```
> Added Advanced Search Option

- README.md
- openfoodfacts/__init__.py
**Problem**
Readme is not updated with the new functionalities.
Getting JSONDecodeError on running some functions.
**Solution**
Updated Readme, added a new part to for search-related instructions.
Fix #15
> Updated Readme & Fixed JSONDecodeError

- openfoodfacts/__init__.py
- openfoodfacts/products.py
- openfoodfacts/utils.py
**Problem**
Currently, there is no way to specify geography of the product
**Solution**
Updated the code to be able to specify the location
Example
```
brands = openfoodfacts.facets.get_brands(locale='in')
```
Fix #16
> Allow to specify locale

- openfoodfacts/__init__.py
- openfoodfacts/products.py
- openfoodfacts/utils.py
**Problem**
No function to make custom URLs.
**Solution**
Added a helper function build_url() to make URL building process easier
> Added build_url()

- README.md
- openfoodfacts/__init__.py
- openfoodfacts/openpetfoodfacts.py
- openfoodfacts/utils.py
**Problem**
1) No way to access openpetfoodfacts
2) Readme not up to date
**Solution**
1) Added file to perform functions related openpetfoodfacts
2) Updated Readme
Fix #44
> Adds openpetfoodfacts & Updates Readme

- openfoodfacts/__init__.py
- openfoodfacts/products.py
- openfoodfacts/utils.py
**Problem**
Code was a bit hard to read and it was not possible to login without using the command prompt.
**Solution**
I did some improvements to make it lighter and more readable:
* Create a new login function to allow programmatic login. Previous function is now based on this one.
* Do not run too complex functions in parameters, extract them as variables.
* Use only snake case for variable names.
* Simplify imagefield dict building.
* Do not use single letter variable names
* Use dictionnary (maps) instead of nested else/if
* Avoid repetitive code
> Code improvements

- README.md
**Problem**
* There was no contributing instruction.
* Contributors were not credited in the README.
**Solution**
* Add some basic information on how to contribute
* Add the list of code contributors
> Add contributing and contributors info to the README

- README.md
**Problem**
Image was previously aligned with a fixed number of '=' symbols, producing inconsistent results.
**Solution**
Used HTML to properly align it. Width used is the width of the image itself.
> Align image to center

- README.md
**Problem**
Anubhav is nom part of the maintainers but he is still listed as a contributor. 
**Solution**
Move Anubhav from the contributor list to the maintainer list.
> Move Anubhav from contributor to maintainer list

- openfoodfacts/__init__.py
- openfoodfacts/utils.py
**Problem**
get_ingredients() returns an empty list when called with "fr" and "world"
**Solution**
The URL for the JSON file was changed
from:-
`https://world.openfoodfacts.org/ingredients.json`
to 
`https://world.openfoodfacts.org/state/complete/ingredients/1.json`
> Fix #51: Solves ValueError on get_ingredients()

- .coveragerc
- .travis.yml
- README.md
**Problem**
Coverage information is missing.
**Solution**
This PR adds coverage support and [codecov.io](https://codecov.io/) integration.
> Add coverage support

- README.rst
- publish.sh
- setup.py
This PR adds files to setup a package for PyPi #41
> Add files for package setup

- .travis.yml
**Problem**
Pep8 package is deprecated
**Solution**
Use `pycodestyle`
> Replace deprecated pep8 with pycodestyle

- README.md
- README.rst
- openfoodfacts/__init__.py
The package is finally on [PyPi](https://pypi.org/project/openfoodfacts/) ✌🏻 🎉 
This PR adds info on READMEs about the package.
I also updated the version to make a new upload on PyPi and add myself to contributors if it's ok for you 😄 
Thanks @teolemon for the access to PyPi!
> Update READMEs with package information
